import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

// Verified PlantType data with sources from university extensions and USDA
const VERIFIED_PLANT_TYPES = [
  {
    plant_type_code: 'PT_POTATO',
    common_name: 'Potato',
    scientific_name: 'Solanum tuberosum',
    category: 'vegetable',
    plant_family: 'Solanaceae',
    plant_group: 'Vegetables',
    icon: '🥔',
    color: '#c9a87c',
    is_perennial: false,
    typical_spacing_min: 10,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 90,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell Vegetable MD Online, UMN Extension. Spacing 10-12" within row, 30-36" between rows.'
  },
  {
    plant_type_code: 'PT_PEA',
    common_name: 'Pea',
    scientific_name: 'Pisum sativum',
    category: 'vegetable',
    plant_family: 'Fabaceae',
    plant_group: 'Vegetables',
    icon: '🫛',
    color: '#7cb342',
    is_perennial: false,
    typical_spacing_min: 2,
    typical_spacing_max: 4,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: true,
    default_days_to_maturity: 60,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, OSU Extension. Direct sow 2-4 weeks before last frost. Spacing 2-4" in rows 18-24" apart.'
  },
  {
    plant_type_code: 'PT_BEAN_BUSH',
    common_name: 'Bean (Bush)',
    scientific_name: 'Phaseolus vulgaris',
    category: 'vegetable',
    plant_family: 'Fabaceae',
    plant_group: 'Vegetables',
    icon: '🫘',
    color: '#8bc34a',
    is_perennial: false,
    typical_spacing_min: 3,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 55,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell Vegetable MD, UMN Extension. Direct sow after frost. Bush beans 3-6" apart, rows 18-24" apart.'
  },
  {
    plant_type_code: 'PT_BEAN_POLE',
    common_name: 'Bean (Pole)',
    scientific_name: 'Phaseolus vulgaris',
    category: 'vegetable',
    plant_family: 'Fabaceae',
    plant_group: 'Vegetables',
    icon: '🫘',
    color: '#7cb342',
    is_perennial: false,
    typical_spacing_min: 6,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: true,
    default_days_to_maturity: 65,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell Vegetable MD, OSU Extension. Pole beans 6-12" apart with trellis. Rows 30-36" apart.'
  },
  {
    plant_type_code: 'PT_SUMMER_SQUASH',
    common_name: 'Summer Squash',
    scientific_name: 'Cucurbita pepo',
    category: 'vegetable',
    plant_family: 'Cucurbitaceae',
    plant_group: 'Vegetables',
    icon: '🥒',
    color: '#ffc107',
    is_perennial: false,
    typical_spacing_min: 24,
    typical_spacing_max: 36,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 50,
    default_start_indoors_weeks: 2,
    default_transplant_weeks: 0,
    notes: 'Sources: UMN Extension, Cornell. Yellow squash, pattypan. Bush types 24-36" apart, vining types 36-48" apart.'
  },
  {
    plant_type_code: 'PT_WINTER_SQUASH',
    common_name: 'Winter Squash',
    scientific_name: 'Cucurbita moschata',
    category: 'vegetable',
    plant_family: 'Cucurbitaceae',
    plant_group: 'Vegetables',
    icon: '🎃',
    color: '#ff9800',
    is_perennial: false,
    typical_spacing_min: 36,
    typical_spacing_max: 60,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 95,
    default_start_indoors_weeks: 3,
    default_transplant_weeks: 0,
    notes: 'Sources: UMN Extension, Cornell. Butternut, acorn. Spacing 36-60" depending on variety. C. maxima and C. moschata species.'
  },
  {
    plant_type_code: 'PT_PUMPKIN',
    common_name: 'Pumpkin',
    scientific_name: 'Cucurbita pepo',
    category: 'vegetable',
    plant_family: 'Cucurbitaceae',
    plant_group: 'Vegetables',
    icon: '🎃',
    color: '#ff5722',
    is_perennial: false,
    typical_spacing_min: 48,
    typical_spacing_max: 72,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 100,
    default_start_indoors_weeks: 3,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Spacing varies by variety: small pie pumpkins 48-60", large carving types 60-72".'
  },
  {
    plant_type_code: 'PT_WATERMELON',
    common_name: 'Watermelon',
    scientific_name: 'Citrullus lanatus',
    category: 'fruit',
    plant_family: 'Cucurbitaceae',
    plant_group: 'Fruits & Berries',
    icon: '🍉',
    color: '#e91e63',
    is_perennial: false,
    typical_spacing_min: 36,
    typical_spacing_max: 60,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 80,
    default_start_indoors_weeks: 3,
    default_transplant_weeks: 0,
    notes: 'Sources: UMN Extension, NC State. Bush types 36-48", vining types 60-72". Requires warm soil (70°F+).'
  },
  {
    plant_type_code: 'PT_CANTALOUPE',
    common_name: 'Cantaloupe',
    scientific_name: 'Cucumis melo',
    category: 'fruit',
    plant_family: 'Cucurbitaceae',
    plant_group: 'Fruits & Berries',
    icon: '🍈',
    color: '#ffb74d',
    is_perennial: false,
    typical_spacing_min: 24,
    typical_spacing_max: 36,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 80,
    default_start_indoors_weeks: 3,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Muskmelon group. 24-36" apart in rows 48-72" apart.'
  },
  {
    plant_type_code: 'PT_SWEET_CORN',
    common_name: 'Sweet Corn',
    scientific_name: 'Zea mays',
    category: 'vegetable',
    plant_family: 'Poaceae',
    plant_group: 'Vegetables',
    icon: '🌽',
    color: '#ffeb3b',
    is_perennial: false,
    typical_spacing_min: 8,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 75,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Direct sow 8-12" apart in blocks (not single rows) for pollination. Rows 30-36" apart.'
  },
  {
    plant_type_code: 'PT_SPINACH',
    common_name: 'Spinach',
    scientific_name: 'Spinacia oleracea',
    category: 'vegetable',
    plant_family: 'Amaranthaceae',
    plant_group: 'Vegetables',
    icon: '🥬',
    color: '#4caf50',
    is_perennial: false,
    typical_spacing_min: 3,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 40,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Cool-season crop. 3-6" apart in rows 12-18" apart. Bolts in hot weather.'
  },
  {
    plant_type_code: 'PT_SWISS_CHARD',
    common_name: 'Swiss Chard',
    scientific_name: 'Beta vulgaris',
    category: 'vegetable',
    plant_family: 'Amaranthaceae',
    plant_group: 'Vegetables',
    icon: '🥬',
    color: '#c62828',
    is_perennial: false,
    typical_spacing_min: 6,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 55,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Same species as beet. 6-12" apart in rows 18-24" apart.'
  },
  {
    plant_type_code: 'PT_BEET',
    common_name: 'Beet',
    scientific_name: 'Beta vulgaris',
    category: 'vegetable',
    plant_family: 'Amaranthaceae',
    plant_group: 'Vegetables',
    icon: '🥕',
    color: '#880e4f',
    is_perennial: false,
    typical_spacing_min: 3,
    typical_spacing_max: 4,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 55,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Direct sow 3-4" apart (thin if needed). Rows 12-18" apart.'
  },
  {
    plant_type_code: 'PT_RADISH',
    common_name: 'Radish',
    scientific_name: 'Raphanus sativus',
    category: 'vegetable',
    plant_family: 'Brassicaceae',
    plant_group: 'Vegetables',
    icon: '🥕',
    color: '#e57373',
    is_perennial: false,
    typical_spacing_min: 1,
    typical_spacing_max: 2,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 25,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Fast-growing. Direct sow 1-2" apart, rows 12" apart.'
  },
  {
    plant_type_code: 'PT_CABBAGE',
    common_name: 'Cabbage',
    scientific_name: 'Brassica oleracea var. capitata',
    category: 'vegetable',
    plant_family: 'Brassicaceae',
    plant_group: 'Vegetables',
    icon: '🥬',
    color: '#81c784',
    is_perennial: false,
    typical_spacing_min: 12,
    typical_spacing_max: 18,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 70,
    default_start_indoors_weeks: 6,
    default_transplant_weeks: -2,
    notes: 'Sources: Cornell, UMN Extension. Cool-season crop. Transplant 2-4 weeks before last frost. 12-18" apart.'
  },
  {
    plant_type_code: 'PT_CAULIFLOWER',
    common_name: 'Cauliflower',
    scientific_name: 'Brassica oleracea var. botrytis',
    category: 'vegetable',
    plant_family: 'Brassicaceae',
    plant_group: 'Vegetables',
    icon: '🥦',
    color: '#f5f5f5',
    is_perennial: false,
    typical_spacing_min: 18,
    typical_spacing_max: 24,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 75,
    default_start_indoors_weeks: 6,
    default_transplant_weeks: -2,
    notes: 'Sources: UMN Extension, Cornell. More sensitive than broccoli. 18-24" apart, rows 24-36" apart.'
  },
  {
    plant_type_code: 'PT_BRUSSELS',
    common_name: 'Brussels Sprouts',
    scientific_name: 'Brassica oleracea var. gemmifera',
    category: 'vegetable',
    plant_family: 'Brassicaceae',
    plant_group: 'Vegetables',
    icon: '🥬',
    color: '#66bb6a',
    is_perennial: false,
    typical_spacing_min: 18,
    typical_spacing_max: 24,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 95,
    default_start_indoors_weeks: 6,
    default_transplant_weeks: -2,
    notes: 'Sources: Cornell, UMN Extension. Long-season cool-season crop. 18-24" apart. Best after light frost.'
  },
  {
    plant_type_code: 'PT_TURNIP',
    common_name: 'Turnip',
    scientific_name: 'Brassica rapa',
    category: 'vegetable',
    plant_family: 'Brassicaceae',
    plant_group: 'Vegetables',
    icon: '🥕',
    color: '#ab47bc',
    is_perennial: false,
    typical_spacing_min: 4,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 50,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Cool-season root crop. Direct sow 4-6" apart, rows 15-18" apart.'
  },
  {
    plant_type_code: 'PT_GARLIC',
    common_name: 'Garlic',
    scientific_name: 'Allium sativum',
    category: 'vegetable',
    plant_family: 'Amaryllidaceae',
    plant_group: 'Vegetables',
    icon: '🧄',
    color: '#eeeeee',
    is_perennial: false,
    typical_spacing_min: 4,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 240,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Plant cloves in fall. 4-6" apart, rows 12-18" apart. Harvest following summer.'
  },
  {
    plant_type_code: 'PT_LEEK',
    common_name: 'Leek',
    scientific_name: 'Allium ampeloprasum',
    category: 'vegetable',
    plant_family: 'Amaryllidaceae',
    plant_group: 'Vegetables',
    icon: '🧅',
    color: '#aed581',
    is_perennial: false,
    typical_spacing_min: 4,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 120,
    default_start_indoors_weeks: 10,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Long-season crop. Start indoors 10-12 weeks before transplant. 4-6" apart.'
  },
  {
    plant_type_code: 'PT_SCALLION',
    common_name: 'Scallion',
    scientific_name: 'Allium fistulosum',
    category: 'vegetable',
    plant_family: 'Amaryllidaceae',
    plant_group: 'Vegetables',
    icon: '🧅',
    color: '#9ccc65',
    is_perennial: false,
    typical_spacing_min: 1,
    typical_spacing_max: 2,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 60,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Green onion/bunching onion. Direct sow 1-2" apart, harvest young.'
  },
  {
    plant_type_code: 'PT_CHIVES',
    common_name: 'Chives',
    scientific_name: 'Allium schoenoprasum',
    category: 'herb',
    plant_family: 'Amaryllidaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#7cb342',
    is_perennial: true,
    typical_spacing_min: 8,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 75,
    default_start_indoors_weeks: 8,
    default_transplant_weeks: -2,
    notes: 'Sources: Cornell, UMN Extension. Perennial herb. 8-12" apart. Divide clumps every 3-4 years.'
  },
  {
    plant_type_code: 'PT_PARSLEY',
    common_name: 'Parsley',
    scientific_name: 'Petroselinum crispum',
    category: 'herb',
    plant_family: 'Apiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#4caf50',
    is_perennial: false,
    typical_spacing_min: 6,
    typical_spacing_max: 10,
    typical_sun: 'partial_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 70,
    default_start_indoors_weeks: 8,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Biennial grown as annual. Slow germination. 6-10" apart.'
  },
  {
    plant_type_code: 'PT_CILANTRO',
    common_name: 'Cilantro',
    scientific_name: 'Coriandrum sativum',
    category: 'herb',
    plant_family: 'Apiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#8bc34a',
    is_perennial: false,
    typical_spacing_min: 4,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 50,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Cool-season herb. Bolts quickly in heat. 4-6" apart. Succession plant.'
  },
  {
    plant_type_code: 'PT_DILL',
    common_name: 'Dill',
    scientific_name: 'Anethum graveolens',
    category: 'herb',
    plant_family: 'Apiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#9ccc65',
    is_perennial: false,
    typical_spacing_min: 8,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 60,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Direct sow 8-12" apart. Attracts beneficial insects.'
  },
  {
    plant_type_code: 'PT_CELERY',
    common_name: 'Celery',
    scientific_name: 'Apium graveolens',
    category: 'vegetable',
    plant_family: 'Apiaceae',
    plant_group: 'Vegetables',
    icon: '🥬',
    color: '#7cb342',
    is_perennial: false,
    typical_spacing_min: 6,
    typical_spacing_max: 8,
    typical_sun: 'full_sun',
    typical_water: 'high',
    trellis_common: false,
    default_days_to_maturity: 100,
    default_start_indoors_weeks: 10,
    default_transplant_weeks: 0,
    notes: 'Sources: UMN Extension, Cornell. Long-season crop. Needs consistent moisture. 6-8" apart.'
  },
  {
    plant_type_code: 'PT_PARSNIP',
    common_name: 'Parsnip',
    scientific_name: 'Pastinaca sativa',
    category: 'vegetable',
    plant_family: 'Apiaceae',
    plant_group: 'Vegetables',
    icon: '🥕',
    color: '#f5f5dc',
    is_perennial: false,
    typical_spacing_min: 3,
    typical_spacing_max: 6,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 120,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Long-season root crop. Direct sow 3-6" apart. Best after frost.'
  },
  {
    plant_type_code: 'PT_OREGANO',
    common_name: 'Oregano',
    scientific_name: 'Origanum vulgare',
    category: 'herb',
    plant_family: 'Lamiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#7cb342',
    is_perennial: true,
    typical_spacing_min: 12,
    typical_spacing_max: 18,
    typical_sun: 'full_sun',
    typical_water: 'low',
    trellis_common: false,
    default_days_to_maturity: 90,
    default_start_indoors_weeks: 8,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Perennial herb (hardy zones 5-9). 12-18" apart. Drought tolerant.'
  },
  {
    plant_type_code: 'PT_THYME',
    common_name: 'Thyme',
    scientific_name: 'Thymus vulgaris',
    category: 'herb',
    plant_family: 'Lamiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#8bc34a',
    is_perennial: true,
    typical_spacing_min: 8,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'low',
    trellis_common: false,
    default_days_to_maturity: 90,
    default_start_indoors_weeks: 8,
    default_transplant_weeks: 0,
    notes: 'Sources: UMN Extension, Cornell. Perennial herb (zones 5-9). 8-12" apart. Well-drained soil.'
  },
  {
    plant_type_code: 'PT_SAGE',
    common_name: 'Sage',
    scientific_name: 'Salvia officinalis',
    category: 'herb',
    plant_family: 'Lamiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#9e9e9e',
    is_perennial: true,
    typical_spacing_min: 18,
    typical_spacing_max: 24,
    typical_sun: 'full_sun',
    typical_water: 'low',
    trellis_common: false,
    default_days_to_maturity: 75,
    default_start_indoors_weeks: 8,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Perennial herb (zones 5-8). 18-24" apart. Well-drained soil essential.'
  },
  {
    plant_type_code: 'PT_ROSEMARY',
    common_name: 'Rosemary',
    scientific_name: 'Salvia rosmarinus',
    category: 'herb',
    plant_family: 'Lamiaceae',
    plant_group: 'Herbs',
    icon: '🌿',
    color: '#607d8b',
    is_perennial: true,
    typical_spacing_min: 24,
    typical_spacing_max: 36,
    typical_sun: 'full_sun',
    typical_water: 'low',
    trellis_common: false,
    default_days_to_maturity: 90,
    default_start_indoors_weeks: 10,
    default_transplant_weeks: 0,
    notes: 'Sources: UMN Extension, Cornell. Perennial zones 8+, annual elsewhere. 24-36" apart. Excellent drainage required.'
  },
  {
    plant_type_code: 'PT_STRAWBERRY',
    common_name: 'Strawberry',
    scientific_name: 'Fragaria × ananassa',
    category: 'fruit',
    plant_family: 'Rosaceae',
    plant_group: 'Fruits & Berries',
    icon: '🍓',
    color: '#f44336',
    is_perennial: true,
    typical_spacing_min: 12,
    typical_spacing_max: 18,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 365,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Perennial. June-bearing: 12-18" apart. Produces runners. Harvest year 2+.'
  },
  {
    plant_type_code: 'PT_RASPBERRY',
    common_name: 'Raspberry',
    scientific_name: 'Rubus idaeus',
    category: 'fruit',
    plant_family: 'Rosaceae',
    plant_group: 'Fruits & Berries',
    icon: '🫐',
    color: '#c2185b',
    is_perennial: true,
    typical_spacing_min: 18,
    typical_spacing_max: 24,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: true,
    default_days_to_maturity: 730,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Perennial bramble. 18-24" apart, rows 6-8\' apart. Requires support/trellis.'
  },
  {
    plant_type_code: 'PT_BLACKBERRY',
    common_name: 'Blackberry',
    scientific_name: 'Rubus fruticosus',
    category: 'fruit',
    plant_family: 'Rosaceae',
    plant_group: 'Fruits & Berries',
    icon: '🫐',
    color: '#4a148c',
    is_perennial: true,
    typical_spacing_min: 24,
    typical_spacing_max: 36,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: true,
    default_days_to_maturity: 730,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, UMN Extension. Perennial bramble. 24-36" apart, rows 8-10\' apart. Requires trellis.'
  },
  {
    plant_type_code: 'PT_BLUEBERRY',
    common_name: 'Blueberry',
    scientific_name: 'Vaccinium corymbosum',
    category: 'fruit',
    plant_family: 'Ericaceae',
    plant_group: 'Fruits & Berries',
    icon: '🫐',
    color: '#3f51b5',
    is_perennial: true,
    typical_spacing_min: 48,
    typical_spacing_max: 60,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 1095,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: UMN Extension, Cornell. Perennial shrub. Requires acidic soil (pH 4.5-5.5). 48-60" apart. Fruit year 3+.'
  },
  {
    plant_type_code: 'PT_MARIGOLD',
    common_name: 'Marigold',
    scientific_name: 'Tagetes',
    category: 'flower',
    plant_family: 'Asteraceae',
    plant_group: 'Flowers',
    icon: '🌼',
    color: '#ffa726',
    is_perennial: false,
    typical_spacing_min: 8,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 50,
    default_start_indoors_weeks: 6,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, OSU Extension. Annual flower. 8-12" apart. Companion plant for vegetables.'
  },
  {
    plant_type_code: 'PT_CALENDULA',
    common_name: 'Calendula',
    scientific_name: 'Calendula officinalis',
    category: 'flower',
    plant_family: 'Asteraceae',
    plant_group: 'Flowers',
    icon: '🌼',
    color: '#ff9800',
    is_perennial: false,
    typical_spacing_min: 9,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 55,
    default_start_indoors_weeks: 6,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Pot marigold. Cool-season annual. Edible petals. 9-12" apart.'
  },
  {
    plant_type_code: 'PT_NASTURTIUM',
    common_name: 'Nasturtium',
    scientific_name: 'Tropaeolum majus',
    category: 'flower',
    plant_family: 'Tropaeolaceae',
    plant_group: 'Flowers',
    icon: '🌼',
    color: '#ff5722',
    is_perennial: false,
    typical_spacing_min: 10,
    typical_spacing_max: 12,
    typical_sun: 'full_sun',
    typical_water: 'low',
    trellis_common: false,
    default_days_to_maturity: 50,
    default_start_indoors_weeks: null,
    default_transplant_weeks: null,
    notes: 'Sources: Cornell, OSU Extension. Annual flower. Edible flowers/leaves. Direct sow 10-12" apart. Tolerates poor soil.'
  },
  {
    plant_type_code: 'PT_SUNFLOWER',
    common_name: 'Sunflower',
    scientific_name: 'Helianthus annuus',
    category: 'flower',
    plant_family: 'Asteraceae',
    plant_group: 'Flowers',
    icon: '🌻',
    color: '#ffd54f',
    is_perennial: false,
    typical_spacing_min: 12,
    typical_spacing_max: 24,
    typical_sun: 'full_sun',
    typical_water: 'moderate',
    trellis_common: false,
    default_days_to_maturity: 80,
    default_start_indoors_weeks: 4,
    default_transplant_weeks: 0,
    notes: 'Sources: Cornell, UMN Extension. Annual. Spacing varies by variety: dwarf 12", tall 24". Direct sow or transplant.'
  }
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Get PlantGroups and Families
    const [groups, families, existingTypes] = await Promise.all([
      base44.asServiceRole.entities.PlantGroup.list(),
      base44.asServiceRole.entities.PlantFamily.list(),
      base44.asServiceRole.entities.PlantType.filter({ plant_type_code: { $exists: true } })
    ]);

    const groupMap = {};
    groups.forEach(g => groupMap[g.name] = g.id);

    const familyMap = {};
    families.forEach(f => familyMap[f.scientific_name] = f.id);

    const existingCodes = new Set(existingTypes.map(t => t.plant_type_code));

    const created = [];
    const skipped = [];
    const auditLog = [];

    for (const plantData of VERIFIED_PLANT_TYPES) {
      if (existingCodes.has(plantData.plant_type_code)) {
        skipped.push(plantData.plant_type_code);
        continue;
      }

      const plant_group_id = groupMap[plantData.plant_group];
      const plant_family_id = familyMap[plantData.plant_family];

      if (!plant_group_id || !plant_family_id) {
        console.error(`Missing group/family for ${plantData.plant_type_code}`);
        continue;
      }

      const newPlant = await base44.asServiceRole.entities.PlantType.create({
        plant_type_code: plantData.plant_type_code,
        plant_group_id,
        plant_family_id,
        common_name: plantData.common_name,
        scientific_name: plantData.scientific_name,
        category: plantData.category,
        icon: plantData.icon,
        color: plantData.color,
        is_perennial: plantData.is_perennial,
        synonyms: [],
        notes: plantData.notes,
        typical_spacing_min: plantData.typical_spacing_min,
        typical_spacing_max: plantData.typical_spacing_max,
        typical_sun: plantData.typical_sun,
        typical_water: plantData.typical_water,
        trellis_common: plantData.trellis_common,
        default_days_to_maturity: plantData.default_days_to_maturity,
        default_start_indoors_weeks: plantData.default_start_indoors_weeks,
        default_transplant_weeks: plantData.default_transplant_weeks
      });

      created.push(plantData.plant_type_code);
      
      auditLog.push({
        code: plantData.plant_type_code,
        common_name: plantData.common_name,
        scientific_name: plantData.scientific_name,
        category: plantData.category,
        is_perennial: plantData.is_perennial,
        spacing: `${plantData.typical_spacing_min}-${plantData.typical_spacing_max}"`,
        dtm: plantData.default_days_to_maturity,
        sources: plantData.notes.includes('Sources:') ? 'YES' : 'NO'
      });
    }

    return Response.json({
      success: true,
      created: created.length,
      skipped: skipped.length,
      created_codes: created,
      skipped_codes: skipped,
      audit: auditLog
    });

  } catch (error) {
    console.error('Error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});